version: '3'

services:
  db:
    hostname: db
    build:
      context: .
      args:
        GUAC_VERSION: ${GUACAMOLE_VERSION}
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  guacd:
    hostname: guacd
    image: guacamole/guacd:${GUACAMOLE_VERSION}
    restart: always

  guacamole:
    image: guacamole/guacamole:${GUACAMOLE_VERSION}
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  data:
